### ISSUE TITLE
deauth doesnt work 

### ISSUE THREAD

**Issue by Perry2001** [mahadidot/DEVIL-TWIN_esp8266#3]

**Comment by mahadidot** [comment]
Select board > deauther > nodemcu
Not generic esp8266

**Comment by mahadidot** [comment]
Select board > deauther > nodemcu
Not generic esp8266

**Comment by Perry2001** [comment]
yes



![image](https://github.com/mahadidot/DEVIL-TWIN_esp8266/assets/93684750/d9a25c8c-55c3-4d00-bffc-9501cdfc1aa6)
![image](https://github.com/mahadidot/DEVIL-TWIN_esp8266/assets/93684750/31fcef97-0019-4ae2-9483-0d4dfceb69c5)

**Comment by mahadidot** [comment]
I dont have any idea is it works or not on nodemcu v1.
I have nodemcu v3.0 and its working seamlessly.

**Comment by rajat99260** [comment]
deauth doesn't worked on my esp8266 v2

**Comment by qpidsyki** [comment]
![Untitled](https://github.com/mahadidot/DEVIL-TWIN_esp8266/assets/153519621/5c43fcd9-1c09-42b2-acef-a704a3c8571e)

deauth does not work.

![Untitled6](https://github.com/mahadidot/DEVIL-TWIN_esp8266/assets/153519621/60a48665-7935-42d8-b057-5f21213801db)

-lolin nodemcu v3.
